C================Beginning-of-user-specified-instructions===============
C
      integer nndim,nedim,nnvdim,nlevdim,nftrdim,nbedim,nbwe,nb1dim,
     &nrdim,nfdim
c
      PARAMETER(NNDIM=800,NEDIM=2*nnDIM,NFTRDIM=8,NFDIM=3*nndim,
     &           NBEDIM=200)
C
C End of the include file QUODDY.DIM
C
C***********************************************************************
C***********************************************************************
